version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - localnet

######## SALES-ORDER ########

  postgres-sales-order:
    image: postgres:13.3-alpine
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=sales_order_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    container_name: postgres_sales_order_service
    networks:
      - localnet

  sales-order-service:
    image: natal/sales-order-service:1.0
    ports:
      - "8083:8083"
    container_name: sales_order_service
    depends_on:
      - postgres-sales-order
      - rabbitmq
    networks:
      - localnet

######## DELIVERY ########

  postgres-delivery:
    image: postgres:13.3-alpine
    hostname: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=delivery_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    container_name: postgres_delivery_service
    networks:
      - localnet

  delivery-service:
    image: natal/delivery-service:1.0
    ports:
      - "8085:8085"
    container_name: delivery_service
    depends_on:
      - postgres-delivery
      - rabbitmq
    networks:
      - localnet

######## SUBSCRIPTION ########

  postgres-subscription:
    image: postgres:13.3-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=subscription_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    container_name: postgres_subscription_service
    networks:
      - localnet

  subscription-service:
    image: natal/subscription-service:1.0
    ports:
      - "8082:8082"
    container_name: subscription_service
    depends_on:
      - postgres-subscription
    networks:
      - localnet

######## CATALOG ########

  postgres-catalog:
    image: postgres:9.6-alpine
    hostname: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=catalogdb
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_catalog
    networks:
      - localnet

  catalog-service:
    image: natal/catalog-service:1.0
    ports:
      - "8084:8084"
    container_name: catalog_service
    depends_on:
      - postgres-catalog
    networks:
      - localnet

######## ELIGIBILITY ########

  postgres-eligibility:
    image: postgres:13.3-alpine
    hostname: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=eligibility_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    container_name: postgres_eligibility_service
    networks:
      - localnet

  eligibility-service:
    image: natal/eligibility-service:1.0
    ports:
      - "8081:8081"
    container_name: eligibility_service
    depends_on:
      - postgres-eligibility
    networks:
      - localnet

networks:
  localnet:
    driver: bridge