version: '3'
services:
  postgres:
    image: postgres:13.3-alpine
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=sales_order_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    container_name: postgres_sales_order_service

  sales-order-service:
    image: natal/sales-order-service:1.0
    ports:
      - "8081:8081"
    container_name: sales_order_service
    depends_on:
      - postgres
