version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres-sales-order:
    image: postgres:13.3-alpine
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=sales_order_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    container_name: postgres_sales_order_service