server.port: 8083

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/sales_order_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: true