server.port: 8083

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/sales_order_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

rabbitmq:
  queue:
    name: sales_order
  exchange:
    name: sales_order_exchange
  routingkey: test_key

catalog:
  host: localhost:8084

subscription:
  host: localhost:8082